environment:
  name: prod
  project: cdf-bootcamp-65-prod
  validation-type: prod
  selected:
  - modules/

variables:
  modules:
    bootcamp:
      # Variables shared by modul

      data_foundation:
        data_developer_source_id: 5e31295c-42ed-498e-aa26-59b47c99d6f9


      ice_cream_api:
        icapi_extractors_source_id: 1d04c109-7a80-465d-820a-5885aea1bc3b


        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}


      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space

      

      use_cases:
        oee:
          data_pipeline_oee_source_id: 5c098827-d249-4450-9ef4-b2c63551014f

          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}

  selected:
    - modules/bootcamp/data_foundation
    - modules/bootcamp/ice_cream_api
    - modules/bootcamp/use_cases/oee