environment:
  name: test
  project: cdf-bootcamp-65-test
  validation-type: test
  selected:
  - modules/

variables:
  modules:
    bootcamp:
      # Variables shared by modules

      data_foundation:
        data_developer_source_id: d8ef2b98-a78b-421b-9a77-4326cb0f44e4

      ice_cream_api:
        icapi_extractors_source_id: 27195efd-3f53-4772-b9c2-58eb77021d1b

        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}


      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space

      

      use_cases:
        oee:
          data_pipeline_oee_source_id: 84a4eb8d-7c20-4d4b-bd61-309c83d98530

          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}

  selected:
    - modules/bootcamp/data_foundation
    - modules/bootcamp/ice_cream_api
    - modules/bootcamp/use_cases/oee